name: Simple Python App
on: push
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      -   name: Checkout repo
          uses: actions/checkout@v4
      -   name: python setup
          uses: actions/setup-python@v5
          with:
            python-version: '3.13.3'
            cache: 'pip'
      -   name: installing dependencies
          run: pip install -r requirements.txt
      -   name: Test
          run: python test_app.py
      -   name: Run Flask app in the background
          run: |
            nohup python app.py &  
            sleep 5  # 
      -   name: Run tests or perform further actions
          run: |
            curl http://127.0.0.1:5000  
      -   name: Stop Flask app
          run: |
            pkill -f "python app.py"  
